spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://192.168.1.111:3306/sue4j
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    ehcache:
      config: config/ehcache/ehcache.xml
  freemarker:
    charset: UTF-8
    cache: true
mybatis:
  config-location: config/mybatis/mybatis-config.xml
  mapper-locations: config/mybatis/mapper/*.xml
